export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    verifyAdminPin: '/auth/verify-admin-pin',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    completeRegistration: '/auth/complete-registration',
  },
  customers: {
    list: '/customers',
    byId: (id: string) => `/customers/${id}`,
    groups: {
      list: '/customers/groups/list',
      create: '/customers/groups',
      delete: (name: string) => `/customers/groups/${encodeURIComponent(name)}`,
    },
  },
  invoices: {
    list: '/invoices',
    byId: (id: string) => `/invoices/${id}`,
    submit: (id: string) => `/invoices/${id}/submit`,
    cancel: (id: string) => `/invoices/${id}/cancel`,
    amend: (id: string) => `/invoices/${id}/amend`,
    pdf: (id: string) => `/invoices/${id}/pdf`,
    ecfPdfa: (id: string) => `/invoices/${id}/ecf/pdfa`,
    version: (id: string, seq: number) => `/invoices/${id}/versions/${seq}`,
    aplicarSaldoFavor: (id: string) => `/invoices/${id}/aplicar-saldo-favor`,
    removerSaldoFavor: (id: string, paymentEntryId: string) => `/invoices/${id}/aplicar-saldo-favor/${paymentEntryId}`,
    asignarTracking: (id: string) => `/invoices/${id}/asignar-tracking`,
  },
  quotations: {
    list: '/quotations',
    byId: (id: string) => `/quotations/${id}`,
    submit: (id: string) => `/quotations/${id}/submit`,
    convert: (id: string) => `/quotations/${id}/convert`,
    amend: (id: string) => `/quotations/${id}/amend`,
    cancel: (id: string) => `/quotations/${id}/cancel`,
    version: (id: string, seq: number) => `/quotations/${id}/versions/${seq}`,
    pdf: (id: string) => `/quotations/${id}/pdf`,
    duplicateSource: (id: string) => `/quotations/${id}/duplicate-source`,
  },
  creditNotes: {
    list: '/credit-notes',
    byId: (id: string) => `/credit-notes/${id}`,
    submit: (id: string) => `/credit-notes/${id}/submit`,
    refund: (id: string) => `/credit-notes/${id}/refund`,
    aplicarAFactura: (id: string) => `/credit-notes/${id}/aplicar-a-factura`,
    removerAplicacion: (id: string, invoiceId: string) => `/credit-notes/${id}/aplicar-a-factura/${invoiceId}`,
    saldoFavor: (customerId: string) => `/credit-notes/saldo-favor/${customerId}`,
    pdf: (id: string) => `/credit-notes/${id}/pdf`,
  },
  devoluciones: {
    create: '/devoluciones',
    list: '/devoluciones',
    byId: (id: string) => `/devoluciones/${id}`,
    cancelar: (id: string) => `/devoluciones/${id}/cancelar`,
  },
  ecfRecibidos: {
    list: '/ecf/recibidos',
    cargarManual: '/ecf/recibidos/cargar-manual',
    byId: (voucherId: string) => `/ecf/recibidos/${encodeURIComponent(voucherId)}`,
    vincular: (voucherId: string) => `/ecf/recibidos/${encodeURIComponent(voucherId)}/vincular`,
    aprobacionComercial: (voucherId: string) => `/ecf/recibidos/${encodeURIComponent(voucherId)}/aprobacion-comercial`,
  },
  debitNotes: {
    list: '/debit-notes',
    byId: (id: string) => `/debit-notes/${id}`,
    submit: (id: string) => `/debit-notes/${id}/submit`,
    pdf: (id: string) => `/debit-notes/${id}/pdf`,
  },
  catalog: {
    categories: {
      list: '/catalog/categories',
      byId: (id: string) => `/catalog/categories/${id}`,
    },
    brands: {
      list: '/catalog/brands',
      byId: (id: string) => `/catalog/brands/${id}`,
    },
    items: {
      list: '/catalog/items',
      byId: (id: string) => `/catalog/items/${id}`,
      stock: (id: string) => `/catalog/items/${id}/stock`,
      toggle: (id: string) => `/catalog/items/${id}/toggle`,
      variants: (id: string) => `/catalog/items/${id}/variants`,
      generateVariants: (id: string) => `/catalog/items/${id}/variants/generate`,
      precios: (id: string) => `/catalog/items/${id}/precios`,
    },
    bundles: {
      list: '/catalog/bundles',
      byId: (id: string) => `/catalog/bundles/${id}`,
    },
    pricingRules: {
      list: '/catalog/pricing-rules',
      byId: (id: string) => `/catalog/pricing-rules/${id}`,
      toggle: (id: string) => `/catalog/pricing-rules/${id}/toggle`,
    },
    cuentasPorPagar: {
      list: '/catalog/cuentas-por-pagar',
      byId: (id: string) => `/catalog/cuentas-por-pagar/${id}`,
    },
  },
  suppliers: {
    list: '/suppliers',
    byId: (id: string) => `/suppliers/${id}`,
    purchases: (id: string) => `/suppliers/${id}/purchases`,
  },
  inventory: {
    list: '/inventory',
    summary: '/inventory/summary',
    warehouses: '/inventory/warehouses',
    history: '/inventory/history',
    historyByItem: (itemCode: string) => `/inventory/history/${itemCode}`,
    lotes: '/inventory/lotes',
    seriales: '/inventory/seriales',
    counts: {
      list: '/inventory/counts',
      template: '/inventory/counts/template',
      byId: (id: string) => `/inventory/counts/${id}`,
      submit: (id: string) => `/inventory/counts/${id}/submit`,
    },
    zonas: {
      list: '/inventory/zonas',
      byId: (id: string) => `/inventory/zonas/${id}`,
    },
    ubicaciones: {
      list: '/inventory/ubicaciones',
      byId: (id: string) => `/inventory/ubicaciones/${id}`,
      byItem: (itemCode: string) => `/inventory/ubicaciones/item/${itemCode}`,
      asignar: '/inventory/ubicaciones/asignar',
      asignarById: (id: string) => `/inventory/ubicaciones/asignar/${id}`,
      pendientes: '/inventory/ubicaciones/pendientes',
      distribuir: '/inventory/ubicaciones/distribuir',
      mover: '/inventory/ubicaciones/mover',
      movimientos: '/inventory/ubicaciones/movimientos',
    },
  },
  compras: {
    list: '/compras',
    byId: (id: string) => `/compras/${id}`,
    submit: (id: string) => `/compras/${id}/submit`,
    cancel: (id: string) => `/compras/${id}/cancel`,
    amend: (id: string) => `/compras/${id}/amend`,
    delete: (id: string) => `/compras/${id}`,
    pdf: (id: string) => `/compras/${id}/pdf`,
    previewAsientos: (id: string) => `/compras/${id}/preview-asientos`,
  },
  purchaseReceipt: {
    list: '/compras/purchase-receipt',
    byId: (id: string) => `/compras/purchase-receipt/${id}`,
    submit: (id: string) => `/compras/purchase-receipt/${id}/submit`,
    cancel: (id: string) => `/compras/purchase-receipt/${id}/cancel`,
    amend: (id: string) => `/compras/purchase-receipt/${id}/amend`,
    facturar: (id: string) => `/compras/purchase-receipt/${id}/facturar`,
  },
  pedidos: {
    list: '/pedidos',
    byId: (id: string) => `/pedidos/${id}`,
    submit: (id: string) => `/pedidos/${id}/submit`,
    cancel: (id: string) => `/pedidos/${id}/cancel`,
    amend: (id: string) => `/pedidos/${id}/amend`,
    version: (id: string, sequence: number) => `/pedidos/${id}/versions/${sequence}`,
    pdf: (id: string) => `/pedidos/${id}/pdf`,
    duplicateSource: (id: string) => `/pedidos/${id}/duplicate-source`,
    facturarApartado: (id: string) => `/pedidos/${id}/facturar-apartado`,
    cancelarApartado: (id: string) => `/pedidos/${id}/cancelar-apartado`,
  },
  gastos: {
    list: '/gastos',
    resumen: '/gastos/resumen',
    byId: (id: string) => `/gastos/${id}`,
    submit: (id: string) => `/gastos/${id}/submit`,
    cancel: (id: string) => `/gastos/${id}/cancel`,
    amend: (id: string) => `/gastos/${id}/amend`,
    previewAsientos: (id: string) => `/gastos/${id}/preview-asientos`,
  },
  devolucionesCompras: {
    list: '/devoluciones-compras',
    byId: (id: string) => `/devoluciones-compras/${id}`,
    create: '/devoluciones-compras',
    update: (id: string) => `/devoluciones-compras/${id}`,
    remove: (id: string) => `/devoluciones-compras/${id}`,
    submit: (id: string) => `/devoluciones-compras/${id}/submit`,
    cancel: (id: string) => `/devoluciones-compras/${id}/cancel`,
    amend: (id: string) => `/devoluciones-compras/${id}/amend`,
    pdf: (id: string) => `/devoluciones-compras/${id}/pdf`,
    saldoFavor: (supplierId: string) => `/devoluciones-compras/saldo-favor/${supplierId}`,
    applyToCxp: (id: string) => `/devoluciones-compras/${id}/aplicar-a-cxp`,
    unapplyCxp: (id: string, invoiceId: string) => `/devoluciones-compras/${id}/aplicar-a-cxp/${invoiceId}`,
  },
  usuarios: {
    list: '/usuarios',
    byEmail: (email: string) => `/usuarios/${email}`,
    enable: (email: string) => `/usuarios/${email}/enable`,
    resetPassword: (email: string) => `/usuarios/${email}/reset-password`,
    sucursales: (email: string) => `/usuarios/${encodeURIComponent(email)}/sucursales`,
    almacenesPermitidos: (email: string) => `/usuarios/${encodeURIComponent(email)}/almacenes-permitidos`,
  },
  roles: {
    list: '/roles',
    byName: (name: string) => `/roles/${encodeURIComponent(name)}`,
  },
  permisos: {
    catalogo: '/permisos/catalogo',
    list: '/permisos',
    reset: '/permisos/reset',
    asignar: '/permisos/asignar',
  },
  sucursales: {
    list: '/sucursales',
    byId: (id: string) => `/sucursales/${encodeURIComponent(id)}`,
  },
  cajas: {
    list: '/pos/cajas',
    byId: (id: string) => `/pos/cajas/${encodeURIComponent(id)}`,
  },
  transferencias: {
    list: '/transferencias',
    byId: (id: string) => `/transferencias/${encodeURIComponent(id)}`,
    confirmar: (id: string) => `/transferencias/${encodeURIComponent(id)}/confirmar`,
    cancelar: (id: string) => `/transferencias/${encodeURIComponent(id)}/cancelar`,
  },
  cuentas: {
    list: '/cuentas',
    tree: '/cuentas/tree',
    byId: (id: string) => `/cuentas/${encodeURIComponent(id)}`,
  },
  journalEntry: {
    list: '/journal-entry',
    byId: (id: string) => `/journal-entry/${encodeURIComponent(id)}`,
    submit: (id: string) => `/journal-entry/${encodeURIComponent(id)}/submit`,
    cancel: (id: string) => `/journal-entry/${encodeURIComponent(id)}/cancel`,
  },
  config: {
    empresa: '/config/empresa',
    cobros: '/config/cobros',
    metodosPago: '/config/metodos-pago',
    almacenes: '/config/almacenes',
    uom: '/config/uom',
    uomById: (id: string) => `/config/uom/${encodeURIComponent(id)}`,
    listasPrecio: '/config/listas-precio',
    gruposClientes: '/config/grupos-clientes',
    gruposProveedores: '/config/grupos-proveedores',
    ncf: '/config/ncf',
    ncfById: (id: number) => `/config/ncf/${id}`,
    ncfDisable: (id: number) => `/config/ncf/${id}/disable`,
    ncfEnable: (id: number) => `/config/ncf/${id}/enable`,
    perfil: '/config/perfil',
    cuentasEmpresa: '/config/cuentas-empresa',
    impuestosVentas: '/config/impuestos-ventas',
    impuestosVentasById: (id: string) => `/config/impuestos-ventas/${encodeURIComponent(id)}`,
    impuestosCompras: '/config/impuestos-compras',
    impuestosComprasById: (id: string) => `/config/impuestos-compras/${encodeURIComponent(id)}`,
    itemTaxTemplates: '/config/item-tax-templates',
    itemTaxTemplatesById: (id: string) => `/config/item-tax-templates/${encodeURIComponent(id)}`,
    tasasImpuesto: '/config/tasas-impuesto',
    tasasImpuestoById: (id: string) => `/config/tasas-impuesto/${encodeURIComponent(id)}`,
    gruposClientesById: (id: string) => `/config/grupos-clientes/${encodeURIComponent(id)}`,
    facturacion: '/config/facturacion',
    apartados: '/config/apartados',
    bancos: '/config/bancos',
    denominaciones: '/config/denominaciones',
    denominacionesById: (id: string) => `/config/denominaciones/${encodeURIComponent(id)}`,
    catalogosFiscales: '/config/catalogos-fiscales',
    paises: '/config/paises',
    currencies: '/config/currencies',
    posHabilitar: '/config/pos/habilitar',
    ecf: '/config/ecf',
    ecfSecuencias: '/config/ecf/secuencias',
    ecfSecuenciasAnularRangos: '/config/ecf/secuencias/anular-rangos',
    ecfSecuenciasById: (id: string) => `/config/ecf/secuencias/${encodeURIComponent(id)}`,
    ecfTipos: '/config/ecf/tipos',
    ecfAdminConnect: '/config/ecf/admin/connect',
    ecfAdminClients: '/config/ecf/admin/clients',
    ecfAdminCertificate: '/config/ecf/admin/certificate',
    ecfAdminWebhook: '/config/ecf/admin/webhook',
    ecfCertificacion: '/config/ecf/certificacion',
    ecfContingenciaPendientes: '/config/ecf/contingencia/pendientes',
    ecfContingenciaActivar: '/config/ecf/contingencia/activar',
    ecfContingenciaDesactivar: '/config/ecf/contingencia/desactivar',
    ecfContingenciaFlush: '/config/ecf/contingencia/flush',
  },
  pos: {
    turnoActual: '/pos/turnos/actual',
    turnoAbrir: '/pos/turnos/abrir',
    turnoPreviewCierre: (openingEntryId: string) => `/pos/turnos/${encodeURIComponent(openingEntryId)}/preview-cierre`,
    turnoCerrar: (openingEntryId: string) => `/pos/turnos/${encodeURIComponent(openingEntryId)}/cerrar`,
    turnos: '/pos/turnos',
    turnoById: (id: string) => `/pos/turnos/${encodeURIComponent(id)}`,
    turnoPdf: (id: string) => `/pos/turnos/${encodeURIComponent(id)}/pdf`,
  },
  caja: {
    pendientes: '/caja/pendientes',
    cobrar: (id: string) => `/caja/facturas/${encodeURIComponent(id)}/cobrar`,
    porCobrar: '/caja/por-cobrar',
    completarCobro: (id: string) => `/caja/facturas/${encodeURIComponent(id)}/completar-cobro`,
    descartar: (id: string) => `/caja/facturas/${encodeURIComponent(id)}`,
  },
  ejercicioFiscal: {
    list: '/config/ejercicio-fiscal',
    vigente: '/config/ejercicio-fiscal/vigente',
    byId: (id: string) => `/config/ejercicio-fiscal/${encodeURIComponent(id)}`,
    close: (id: string) => `/config/ejercicio-fiscal/${encodeURIComponent(id)}/close`,
    reopen: (id: string) => `/config/ejercicio-fiscal/${encodeURIComponent(id)}/reopen`,
  },
  cierrePeriodo: {
    list: '/contabilidad/cierre-periodo',
    byId: (id: string) => `/contabilidad/cierre-periodo/${encodeURIComponent(id)}`,
    submit: (id: string) => `/contabilidad/cierre-periodo/${encodeURIComponent(id)}/submit`,
  },
  cobros: {
    list: '/cobros',
    pendientes: '/cobros/pendientes',
    aging: '/cobros/aging',
    semaforo: '/cobros/semaforo',
    semaforoByCustomer: (id: string) => `/cobros/semaforo/${id}`,
    historial: (id: string) => `/cobros/historial/${id}`,
    byId: (id: string) => `/cobros/${id}`,
    submit: (id: string) => `/cobros/${id}/submit`,
    cancel: (id: string) => `/cobros/${id}/cancel`,
    saldoFavor: (customerId: string) => `/cobros/saldo-favor/${customerId}`,
    estadoCuenta: (customerId: string) => `/cobros/estado-cuenta/${customerId}`,
    estadoCuentaPdf: (customerId: string) => `/cobros/estado-cuenta/${customerId}/pdf`,
    pdf: (id: string) => `/cobros/${id}/pdf`,
  },
  pagos: {
    list: '/pagos',
    pendientes: '/pagos/pendientes',
    aging: '/pagos/aging',
    historial: (supplierId: string) => `/pagos/historial/${encodeURIComponent(supplierId)}`,
    byId: (id: string) => `/pagos/${id}`,
    submit: (id: string) => `/pagos/${id}/submit`,
    cancel: (id: string) => `/pagos/${id}/cancel`,
    saldoFavor: (supplierId: string) => `/pagos/saldo-favor/${encodeURIComponent(supplierId)}`,
    aplicarSaldoFavor: '/pagos/aplicar-saldo-favor',
    imprimir: (id: string) => `/pagos/${encodeURIComponent(id)}/imprimir`,
  },
  reportes: {
    ventas: '/reportes/ventas',
    ventasPdf: '/reportes/ventas/pdf',
    balanceGeneral: '/reportes/balance-general',
    balanceGeneralPdf: '/reportes/balance-general/pdf',
    ingresosEgresos: '/reportes/ingresos-egresos',
    ingresosEgresosPdf: '/reportes/ingresos-egresos/pdf',
    r606: '/reportes/dgii/606',
    r607: '/reportes/dgii/607',
    r608: '/reportes/dgii/608',
    inventarioValoracion: '/reportes/inventario/valoracion',
    inventarioValoracionPdf: '/reportes/inventario/valoracion/pdf',
    inventarioMovimientos: '/reportes/inventario/movimientos',
    inventarioMovimientosPdf: '/reportes/inventario/movimientos/pdf',
    cxcAging: '/reportes/cxc/aging',
    cxcAgingPdf: '/reportes/cxc/aging/pdf',
    cxpAging: '/reportes/cxp/aging',
    cxpAgingPdf: '/reportes/cxp/aging/pdf',
    cajaCuadre: '/reportes/caja/cuadre',
    cajaCuadrePdf: '/reportes/caja/cuadre/pdf',
    libroDiario: '/reportes/libro-diario',
    libroDiarioPdf: '/reportes/libro-diario/pdf',
    libroMayor: '/reportes/libro-mayor',
    libroMayorPdf: '/reportes/libro-mayor/pdf',
    cuadreTurno: '/reportes/pos/cuadre-turno',
    cuadreTurnoPdf: '/reportes/pos/cuadre-turno/pdf',
    corteCajaDia: '/reportes/pos/corte-caja-dia',
    corteCajaDiaPdf: '/reportes/pos/corte-caja-dia/pdf',
  },
  cuentasMovimientos: {
    byId: (id: string) => `/cuentas/${encodeURIComponent(id)}/movimientos`,
  },
  centrosCosto: {
    list: '/centros-costo',
    tree: '/centros-costo/tree',
    byId: (id: string) => `/centros-costo/${encodeURIComponent(id)}`,
  },
  cuentasBancarias: {
    list: '/cuentas-bancarias',
    byId: (id: string) => `/cuentas-bancarias/${encodeURIComponent(id)}`,
    balance: (id: string) => `/cuentas-bancarias/${encodeURIComponent(id)}/balance`,
    tipos: '/cuentas-bancarias/tipos',
    bancos: {
      list: '/cuentas-bancarias/bancos',
      byId: (id: string) => `/cuentas-bancarias/bancos/${encodeURIComponent(id)}`,
    },
  },
  tesoreria: {
    tiposDocumento: {
      list: '/tesoreria/tipos-documento',
      byId: (id: string) => `/tesoreria/tipos-documento/${encodeURIComponent(id)}`,
      disable: (id: string) => `/tesoreria/tipos-documento/${encodeURIComponent(id)}/disable`,
    },
    emisiones: {
      list: '/tesoreria/emisiones',
      byId: (id: string) => `/tesoreria/emisiones/${encodeURIComponent(id)}`,
      submit: (id: string) => `/tesoreria/emisiones/${encodeURIComponent(id)}/submit`,
      cancel: (id: string) => `/tesoreria/emisiones/${encodeURIComponent(id)}/cancel`,
      pendientes: (supplierId: string) => `/tesoreria/emisiones/pendientes/${encodeURIComponent(supplierId)}`,
      siguienteCheque: '/tesoreria/emisiones/siguiente-cheque',
      imprimir: (id: string) => `/tesoreria/emisiones/${encodeURIComponent(id)}/imprimir`,
      previewAsientos: (id: string) => `/tesoreria/emisiones/${encodeURIComponent(id)}/preview-asientos`,
    },
    depositos: {
      list: '/tesoreria/depositos',
      byId: (id: string) => `/tesoreria/depositos/${encodeURIComponent(id)}`,
      submit: (id: string) => `/tesoreria/depositos/${encodeURIComponent(id)}/submit`,
      cancel: (id: string) => `/tesoreria/depositos/${encodeURIComponent(id)}/cancel`,
      pendientes: (partyId: string) => `/tesoreria/depositos/pendientes/${encodeURIComponent(partyId)}`,
      previewAsientos: (id: string) => `/tesoreria/depositos/${encodeURIComponent(id)}/preview-asientos`,
    },
    transferenciasInternas: {
      list: '/tesoreria/transferencias-internas',
      byId: (id: string) => `/tesoreria/transferencias-internas/${encodeURIComponent(id)}`,
      submit: (id: string) => `/tesoreria/transferencias-internas/${encodeURIComponent(id)}/submit`,
      cancel: (id: string) => `/tesoreria/transferencias-internas/${encodeURIComponent(id)}/cancel`,
      previewAsientos: (id: string) => `/tesoreria/transferencias-internas/${encodeURIComponent(id)}/preview-asientos`,
    },
    movimientos: {
      list: '/tesoreria/movimientos',
      resumen: '/tesoreria/movimientos/resumen',
    },
    chequePrintTemplates: {
      list: '/tesoreria/cheque-print-templates',
      byId: (id: string) => `/tesoreria/cheque-print-templates/${encodeURIComponent(id)}`,
      regenerar: (id: string) => `/tesoreria/cheque-print-templates/${encodeURIComponent(id)}/regenerar`,
    },
    cheques: {
      list: '/tesoreria/cheques',
      siguiente: '/tesoreria/cheques/siguiente',
      byId: (id: string) => `/tesoreria/cheques/${encodeURIComponent(id)}`,
      anular: (id: string) => `/tesoreria/cheques/${encodeURIComponent(id)}/anular`,
      imprimir: (id: string) => `/tesoreria/cheques/${encodeURIComponent(id)}/imprimir`,
    },
  },
  departamentos: {
    list: '/departamentos',
    tree: '/departamentos/tree',
    byId: (id: string) => `/departamentos/${encodeURIComponent(id)}`,
  },
  retenciones: {
    list: '/config/retenciones',
    byId: (id: string) => `/config/retenciones/${encodeURIComponent(id)}`,
  },
  costosImportacion: {
    list: '/compras/costos-importacion',
    byId: (id: string) => `/compras/costos-importacion/${encodeURIComponent(id)}`,
    submit: (id: string) => `/compras/costos-importacion/${encodeURIComponent(id)}/submit`,
    cancel: (id: string) => `/compras/costos-importacion/${encodeURIComponent(id)}/cancel`,
    tiposDocumento: '/compras/costos-importacion/tipos-documento',
  },
  settings: {
    accounts: '/config/accounts-settings',
    stock: '/config/stock-settings',
    selling: '/config/selling-settings',
    buying: '/config/buying-settings',
    seguridad: '/config/seguridad',
  },
  notificaciones: {
    tipos: '/notificaciones/tipos',
    tipoByCodigo: (codigo: string) => `/notificaciones/tipos/${encodeURIComponent(codigo)}`,
    canalEmail: '/notificaciones/canales/email',
    logs: '/notificaciones/logs',
    logsResumen: '/notificaciones/logs/resumen',
    probar: (codigo: string) => `/notificaciones/tipos/${encodeURIComponent(codigo)}/probar`,
  },
} as const
