export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    verifyAdminPin: '/auth/verify-admin-pin',
  },
  customers: {
    list: '/customers',
    byId: (id: string) => `/customers/${id}`,
    groups: {
      list: '/customers/groups/list',
      create: '/customers/groups',
      delete: (name: string) => `/customers/groups/${encodeURIComponent(name)}`,
    },
  },
  invoices: {
    list: '/invoices',
    byId: (id: string) => `/invoices/${id}`,
    submit: (id: string) => `/invoices/${id}/submit`,
    cancel: (id: string) => `/invoices/${id}/cancel`,
    amend: (id: string) => `/invoices/${id}/amend`,
    pdf: (id: string) => `/invoices/${id}/pdf`,
    version: (id: string, seq: number) => `/invoices/${id}/versions/${seq}`,
    aplicarSaldoFavor: (id: string) => `/invoices/${id}/aplicar-saldo-favor`,
  },
  quotations: {
    list: '/quotations',
    byId: (id: string) => `/quotations/${id}`,
    submit: (id: string) => `/quotations/${id}/submit`,
    convert: (id: string) => `/quotations/${id}/convert`,
    amend: (id: string) => `/quotations/${id}/amend`,
    cancel: (id: string) => `/quotations/${id}/cancel`,
    version: (id: string, seq: number) => `/quotations/${id}/versions/${seq}`,
    pdf: (id: string) => `/quotations/${id}/pdf`,
    duplicateSource: (id: string) => `/quotations/${id}/duplicate-source`,
  },
  creditNotes: {
    list: '/credit-notes',
    byId: (id: string) => `/credit-notes/${id}`,
    submit: (id: string) => `/credit-notes/${id}/submit`,
    refund: (id: string) => `/credit-notes/${id}/refund`,
  },
  devoluciones: {
    create: '/devoluciones',
  },
  debitNotes: {
    list: '/debit-notes',
    byId: (id: string) => `/debit-notes/${id}`,
    submit: (id: string) => `/debit-notes/${id}/submit`,
  },
  catalog: {
    categories: {
      list: '/catalog/categories',
      byId: (id: string) => `/catalog/categories/${id}`,
    },
    brands: {
      list: '/catalog/brands',
      byId: (id: string) => `/catalog/brands/${id}`,
    },
    items: {
      list: '/catalog/items',
      byId: (id: string) => `/catalog/items/${id}`,
      stock: (id: string) => `/catalog/items/${id}/stock`,
      toggle: (id: string) => `/catalog/items/${id}/toggle`,
      variants: (id: string) => `/catalog/items/${id}/variants`,
      generateVariants: (id: string) => `/catalog/items/${id}/variants/generate`,
    },
    bundles: {
      list: '/catalog/bundles',
      byId: (id: string) => `/catalog/bundles/${id}`,
    },
  },
  suppliers: {
    list: '/suppliers',
    byId: (id: string) => `/suppliers/${id}`,
    purchases: (id: string) => `/suppliers/${id}/purchases`,
  },
  inventory: {
    list: '/inventory',
    summary: '/inventory/summary',
    warehouses: '/inventory/warehouses',
    history: '/inventory/history',
    historyByItem: (itemCode: string) => `/inventory/history/${itemCode}`,
    lotes: '/inventory/lotes',
    seriales: '/inventory/seriales',
    counts: {
      list: '/inventory/counts',
      template: '/inventory/counts/template',
      byId: (id: string) => `/inventory/counts/${id}`,
      submit: (id: string) => `/inventory/counts/${id}/submit`,
    },
  },
  compras: {
    list: '/compras',
    byId: (id: string) => `/compras/${id}`,
    submit: (id: string) => `/compras/${id}/submit`,
    cancel: (id: string) => `/compras/${id}/cancel`,
    amend: (id: string) => `/compras/${id}/amend`,
    return: (id: string) => `/compras/${id}/return`,
    delete: (id: string) => `/compras/${id}`,
  },
  pedidos: {
    list: '/pedidos',
    byId: (id: string) => `/pedidos/${id}`,
    submit: (id: string) => `/pedidos/${id}/submit`,
    cancel: (id: string) => `/pedidos/${id}/cancel`,
    amend: (id: string) => `/pedidos/${id}/amend`,
    version: (id: string, sequence: number) => `/pedidos/${id}/versions/${sequence}`,
    pdf: (id: string) => `/pedidos/${id}/pdf`,
    duplicateSource: (id: string) => `/pedidos/${id}/duplicate-source`,
    facturarApartado: (id: string) => `/pedidos/${id}/facturar-apartado`,
    cancelarApartado: (id: string) => `/pedidos/${id}/cancelar-apartado`,
  },
  gastos: {
    list: '/gastos',
    resumen: '/gastos/resumen',
    byId: (id: string) => `/gastos/${id}`,
    submit: (id: string) => `/gastos/${id}/submit`,
    cancel: (id: string) => `/gastos/${id}/cancel`,
    amend: (id: string) => `/gastos/${id}/amend`,
  },
  usuarios: {
    list: '/usuarios',
    byEmail: (email: string) => `/usuarios/${email}`,
    enable: (email: string) => `/usuarios/${email}/enable`,
    resetPassword: (email: string) => `/usuarios/${email}/reset-password`,
  },
  roles: {
    list: '/roles',
  },
  cuentas: {
    list: '/cuentas',
    tree: '/cuentas/tree',
    byId: (id: string) => `/cuentas/${encodeURIComponent(id)}`,
  },
  journalEntry: {
    list: '/journal-entry',
    byId: (id: string) => `/journal-entry/${encodeURIComponent(id)}`,
    submit: (id: string) => `/journal-entry/${encodeURIComponent(id)}/submit`,
    cancel: (id: string) => `/journal-entry/${encodeURIComponent(id)}/cancel`,
  },
  config: {
    empresa: '/config/empresa',
    cobros: '/config/cobros',
    metodosPago: '/config/metodos-pago',
    almacenes: '/config/almacenes',
    uom: '/config/uom',
    uomById: (id: string) => `/config/uom/${encodeURIComponent(id)}`,
    listasPrecio: '/config/listas-precio',
    gruposClientes: '/config/grupos-clientes',
    gruposProveedores: '/config/grupos-proveedores',
    ncf: '/config/ncf',
    ncfById: (id: number) => `/config/ncf/${id}`,
    ncfDisable: (id: number) => `/config/ncf/${id}/disable`,
    ncfEnable: (id: number) => `/config/ncf/${id}/enable`,
    perfil: '/config/perfil',
    cuentasEmpresa: '/config/cuentas-empresa',
    impuestosVentas: '/config/impuestos-ventas',
    impuestosVentasById: (id: string) => `/config/impuestos-ventas/${encodeURIComponent(id)}`,
    impuestosCompras: '/config/impuestos-compras',
    impuestosComprasById: (id: string) => `/config/impuestos-compras/${encodeURIComponent(id)}`,
    itemTaxTemplates: '/config/item-tax-templates',
    gruposClientesById: (id: string) => `/config/grupos-clientes/${encodeURIComponent(id)}`,
    facturacion: '/config/facturacion',
    apartados: '/config/apartados',
  },
  ejercicioFiscal: {
    list: '/config/ejercicio-fiscal',
    vigente: '/config/ejercicio-fiscal/vigente',
    byId: (id: string) => `/config/ejercicio-fiscal/${encodeURIComponent(id)}`,
    close: (id: string) => `/config/ejercicio-fiscal/${encodeURIComponent(id)}/close`,
    reopen: (id: string) => `/config/ejercicio-fiscal/${encodeURIComponent(id)}/reopen`,
  },
  cierrePeriodo: {
    list: '/contabilidad/cierre-periodo',
    byId: (id: string) => `/contabilidad/cierre-periodo/${encodeURIComponent(id)}`,
    submit: (id: string) => `/contabilidad/cierre-periodo/${encodeURIComponent(id)}/submit`,
  },
  cobros: {
    list: '/cobros',
    pendientes: '/cobros/pendientes',
    aging: '/cobros/aging',
    semaforo: '/cobros/semaforo',
    semaforoByCustomer: (id: string) => `/cobros/semaforo/${id}`,
    historial: (id: string) => `/cobros/historial/${id}`,
    byId: (id: string) => `/cobros/${id}`,
    submit: (id: string) => `/cobros/${id}/submit`,
    cancel: (id: string) => `/cobros/${id}/cancel`,
    saldoFavor: (customerId: string) => `/cobros/saldo-favor/${customerId}`,
  },
  reportes: {
    ventas: '/reportes/ventas',
    balanceGeneral: '/reportes/balance-general',
    ingresosEgresos: '/reportes/ingresos-egresos',
    r606: '/reportes/dgii/606',
    r607: '/reportes/dgii/607',
    r608: '/reportes/dgii/608',
    inventarioValoracion: '/reportes/inventario/valoracion',
    inventarioMovimientos: '/reportes/inventario/movimientos',
    cxcAging: '/reportes/cxc/aging',
    cajaCuadre: '/reportes/caja/cuadre',
    libroDiario: '/reportes/libro-diario',
    libroMayor: '/reportes/libro-mayor',
  },
  cuentasMovimientos: {
    byId: (id: string) => `/cuentas/${encodeURIComponent(id)}/movimientos`,
  },
} as const
